# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10 # This rev is for ruff itself, managed by the hook
    hooks:
    -   id: ruff-format
        args: [--fix]
    -   id: ruff-check # Changed from 'ruff' to 'ruff-check' as per ruff-pre-commit docs
        args: [--fix, --exit-non-zero-on-fix]
        # Configuration for specific lint rules (like flake8-annotations)
        # will be handled in pyproject.toml

-   repo: https://github.com/ComPWA/pyright-pre-commit
    rev: v1.1.400
    hooks:
    -   id: pyright

-   repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
    -   id: nbstripout
