[tool.ruff]
# Other Ruff configurations

[tool.ruff.lint]
extend-select = ["PLR0915", "ANN", "C901"]  # Enable Pylint's "too-many-statements", flake8-annotations, and complex-structure rules

[tool.ruff.lint.pylint]
max-statements = 50  # Set the maximum number of statements per function
